# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "en"
title: "nicolast.be"
title_separator: "&raquo;"
name: "Nicolas Trangez"
description: "My blog."
url: "https://nicolast.be"
baseurl: # the subpath of your site, e.g. "/blog"
repository: "NicolasT/nicolast.github.io"
twitter_username: eikke
github_username: NicolasT
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Brussels # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache


# SEO Related
google_site_verification : "7SXobc1ltJXe4Xqy_ZBZJEVc1sWPi03lIkaHIXCiNqc"

# Social Sharing
twitter:
  username               : &twitter "eikke"
og_image                 : &avatar-nicolas "/assets/images/avatar-nicolas.jpg" # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/eikke"

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-91109342-1"

# Site Author
author:
  name             : "Nicolas T."
  avatar           : *avatar-nicolas # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Software guy, Architect @ <a href='http://scality.com'>Scality</a>. <a href='http://haskell.org'>Haskell</a>'ist, music-lover and startup-minded."
  location         : "🇫🇷 Paris | 🇧🇪 Antwerp"
  email            : "ikke@nicolast.be"
  github           : "NicolasT"
  lastfm           : "eikke"
  linkedin         : "nicolastrangez"
  stackoverflow    : "1285443/nicolas-trangez"
  twitter          : *twitter

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/eikke"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/NicolasT"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
