---
name: Build and deploy the website

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  github-pages:
    name: Build and deploy on GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v3.0.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.124.0
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Build the website using Jekyll
        run: |
            bundle exec \
                jekyll build \
                --verbose \
                --strict_front_matter
        env:
          JEKYLL_ENV: production
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check website links using htmlproofer
        run: |
            bundle exec \
                htmlproofer \
                    --allow-hash-href \
                    --check-favicon \
                    --check-opengraph \
                    --http-status-ignore "999" \
                    _site \
            || echo "htmlproofer failed"
      - name: Upload the website to the 'gh-pages' branch
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
